### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by solaimanhosen** [cmdr2/v8-android#1] opened 2018-12-07 12:20 UTC
Build command failed.
Error while executing process /home/solaiman/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/solaiman/TIZEN-WEB-PROJECTS/Embaded V8/v8-android/jni-test/app/.externalNativeBuild/cmake/debug/x86_64 --target native-lib}
ninja: error: '../../../../libs/x86_64/libv8_base.a', needed by '../../../../build/intermediates/cmake/debug/obj/x86_64/libnative-lib.so', missing and no known rule to make it

**Comment by cmdr2** [comment] 2018-12-08 07:31
I notice that your build architecture is set to x86_64. Are you sure your android device is running x86_64? Usually it'll be something like armeabi-v7a or something similar.

Related reading: https://github.com/cmdr2/v8-android#in-android-studio

**Comment by solaimanhosen** [comment] 2018-12-10 06:07
Build command failed.
Error while executing process /home/solaiman/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/solaiman/TIZEN-WEB-PROJECTS/Embaded V8/v8-android/jni-test/app/.externalNativeBuild/cmake/debug/arm64-v8a --target native-lib}
[1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so
FAILED: : && /home/solaiman/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=aarch64-none-linux-android21 --gcc-toolchain=/home/solaiman/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/solaiman/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem /home/solaiman/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++0x -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /home/solaiman/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/home/solaiman/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  ../../../../libs/arm64-v8a/libv8_base.a ../../../../libs/arm64-v8a/libv8_snapshot.a -llog -latomic -lm "/home/solaiman/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a" "/home/solaiman/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a" && :
/home/solaiman/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld:../../../../libs/arm64-v8a/libv8_base.a: file format not recognized; treating as linker script
/home/solaiman/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld:../../../../libs/arm64-v8a/libv8_base.a:1: syntax error
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


I tried almost all ABIs like (armeabi, armeabi-v7a, arm64-v8a, x86, x86_64). Every time I got same error like previous comment. But while using ABI arm64-v8a, I got the error attached this comment. My device is Samsung Galaxy S9+... I hope I will get advice what else can i do to solve this problem... 

Thanks for replying my comment.

**Comment by cmdr2** [comment] 2018-12-19 06:09
Sorry for the late reply. Here's what I know:
1. The armeabi-v7a folder is present inside 'libs' in the project
2. The build in your case seems to be looking in a different place, hence it isn't able to find 'armeabi-v7a'.
3. Searching for your phone's ABI on Google shows it does support armeabi-v7a, so I'd try to see why your build settings are trying to look in a different location.

I'm sorry I can't be more helpful, did you make any changes to your build settings? Can you try a fresh start (i.e. download the project in a different location, and just hit run)?

Also, does installing this pre-compiled demo APK work on your device? 
https://github.com/cmdr2/v8-android/blob/master/jni-test.apk

**Comment by cmdr2** [comment] 2018-12-26 12:14
Okay, I managed to reproduce this error (and fix it, for myself).

Short answer: if you downloaded the project as a ZIP, try using `git clone` instead.

I think it happens if you downloaded the project as a ZIP instead of using 'git clone'. The two library files (`libv8_base.a` and `libv8_snapshot.a`) are large files, and tracked using git LFS, which means they aren't directly checked into the repository. If you look at the two files in your downloaded folder, you'll see they're actually tiny text files, pointing to where to download the actual file from.

So either you can download the files directly from [libv8_base.a](https://github.com/cmdr2/v8-android/blob/master/jni-test/app/libs/armeabi-v7a/libv8_base.a) and [libv8_snapshot.a](https://github.com/cmdr2/v8-android/blob/master/jni-test/app/libs/armeabi-v7a/libv8_snapshot.a), and replace in your downloaded project, or you can use 'git clone' to get the entire project fresh.

Also, I've added an ABI filter to the gradle file, so even though your ABI is now correct, it'll prevent future users from getting stuck.

**Comment by cmdr2** [comment] 2019-01-10 05:29
Closing this since the reported problem has been tested and fixed on my end. Please feel free to reopen or comment if you're still encountering issues.

**Closed as completed by cmdr2** 2019-01-10 05:29 UTC
