### ISSUE TITLE
Can not compile in Android Studio

### ISSUE THREAD

**Issue by grassel** [cmdr2/v8-android#2] opened 2019-06-04 12:13 UTC
Is this project supposed to compile in Android Studio? 
I am getting the following short error message on Gradle Sync.
   SIMPLE: Error configuring
no further details given.

**Comment by cmdr2** [comment] 2019-06-04 12:45
It compiles on Android Studio 3.2, but I haven't tried 3.3 or 3.4. I'll try upgrading my Android Studio version and see if I can reproduce the problem, but in the meanwhile, can you see if this page helps you? https://github.com/janeasystems/nodejs-mobile/issues/161

**Comment by grassel** [comment] 2019-06-04 18:15
I tried on another computer, with presumably slightly different version of Android Studio, SDK, etc. I installed Android SDK Built Tools 27.0.3. With that gradle sync succeeds. 

Next up, the actual built fails with complain about the pre-build V8 library
in target :app:externalNativeBuildDebug

Any ideas?

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:externalNativeBuildDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.UncheckedException: Build command failed.
Error while executing process /Users/grassel/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
[2/2] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so
FAILED: : && /Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi19 --gcc-toolchain=/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -std=c++0x -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  ../../../../libs/armeabi-v7a/libv8_base.a ../../../../libs/armeabi-v7a/libv8_snapshot.a -llog -latomic -lm && :
/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_base.a:1:9: syntax error, unexpected STRING
/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_base.a: not an object or archive
/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_snapshot.a:1:9: syntax error, unexpected STRING
/Users/grassel/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_snapshot.a: not an object or archive
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:23: error: undefined reference to 'v8::V8::InitializeICU(char const*)'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:24: error: undefined reference to 'v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::__ndk1::unique_ptr<v8::TracingController, std::__ndk1::default_delete<v8::TracingController> >)'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:25: error: undefined reference to 'v8::V8::InitializePlatform(v8::Platform*)'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:26: error: undefined reference to 'v8::V8::Initialize()'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:30: error: undefined reference to 'v8::ArrayBuffer::Allocator::NewDefaultAllocator()'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:31: error: undefined reference to 'v8::Isolate::New(v8::Isolate::CreateParams const&)'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:35: error: undefined reference to 'v8::HandleScope::HandleScope(v8::Isolate*)'
/Volumes/Home_1TB/guido/Playground/github.com/v8-android/jni-test/app/src/main/cpp/native-lib.cpp:38: error: undefined reference to 'v8::Context::New(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>, v8::MaybeLocal<v8::Value>, v8::DeserializeInternalFieldsCallback)'
../../../../libs/include/v8.h:9436: error: undefined reference to 'v8::V8::DisposeGlobal(v8::internal::Object**)'

**Comment by grassel** [comment] 2019-06-04 18:19
I got beyond the gradle sync issue on another computer with another installation of Studio and Tools. What I needed install was Android SDK Build Tools 27.0.3.

**Comment by grassel** [comment] 2019-06-04 18:23
Now, I am facing an issue that the ld complains about symtax error in the provided library(am I supposed to build it myself?)
.... /sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_base.a:1:9: syntax error, unexpected STRING

.... sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../libs/armeabi-v7a/libv8_base.a: not an object or archive

more similar errors follow

Any ideas?

**Comment by cmdr2** [comment] 2019-06-05 09:22
Nice work getting past the previous errors. Regarding the `ld` error, did you use `git clone` to get this repository, or did you download a ZIP file? This error could come if you downloaded a ZIP file instead of cloning the repository, since those `.a` libraries are downloaded via git LFS.

This is pointed out in the [readme](https://github.com/cmdr2/v8-android#in-android-studio), but I can make this note more prominent and visible if this was the problem.

**Comment by cmdr2** [comment] 2019-06-11 05:49
I'm reasonably confident the ZIP-vs-clone was the problem in your second error. Incase that's not the solution, and it's still causing problems, please feel free to reopen (or let me know, I'll reopen).

Closing this for now.

**Closed as completed by cmdr2** 2019-06-11 05:49 UTC
